### ISSUE TITLE
show type and status of account

### ISSUE THREAD

**Issue by dlmueller** [schaary/changeMailAdress#4]
Bei einigen Fällen ist die Namensänderung gar nicht mehr nötig, da die Studenten bereits exmatrikuliert sind. In diesem Fall würde der Typ/Status wie aus dem Adminportal helfen, also z.B. "s-" etc.

**Comment by schaary** [comment]
Es besteht aber die Möglichkeit, dass die Studenten wieder kommen und dann hätte der Account bereits den richtigen Namen ... Wir könnten auch die "abgelaufenen" Accounts grundsätzlich ausblenden. Dann wäre man nicht versucht, noch Änderungen vorzunehmen. Also:

- [] abgelaufenen Accounts ausblenden?
- [] Account-Typ und Account-Status anzeigen und den Bearbeiter selbst entscheiden lassen?

Also David, wie entscheidest Du Dich?

**Comment by dlmueller** [comment]
Ich entscheide mich für:
> Account-Typ und Account-Status anzeigen und den Bearbeiter selbst entscheiden lassen?
